#!/bin/bash

# Whisper Local Setup Guide
# Created by your Audio-to-Text Converter

echo "🎵 Whisper Local Setup - Successfully Installed!"
echo "=============================================="
echo ""
echo "� Checking Dependencies:"
echo "   Whisper: $(which whisper)"
echo "   FFmpeg: $(which ffmpeg)"
echo ""
if ! command -v ffmpeg &> /dev/null; then
    echo "⚠️  IMPORTANT: FFmpeg not found!"
    echo "   Please install it with: brew install ffmpeg"
    echo ""
fi
echo ""
echo "📊 Available Models (will download on first use):"
echo "   • tiny    (39 MB)   - Fast, basic quality"
echo "   • base    (74 MB)   - Good balance"
echo "   • small   (244 MB)  - Better quality"
echo "   • medium  (769 MB)  - High quality"
echo "   • large   (1.5 GB)  - Best quality"
echo ""
echo "🚀 Quick Usage Examples:"
echo "   Basic transcription:"
echo "   whisper audio.mp3"
echo ""
echo "   With specific model:"
echo "   whisper audio.mp3 --model medium"
echo ""
echo "   Save as text file only:"
echo "   whisper audio.mp3 --output_format txt"
echo ""
echo "   Process multiple files:"
echo "   whisper *.mp3 --model small"
echo ""
echo "   For Buddhist content (English with mixed languages):"
echo "   whisper dharma-talk.mp3 --model medium --language English"
echo ""
echo "💡 Tips for Large Files:"
echo "   • No file size limits (unlike 25MB API limit)"
echo "   • Larger models = better accuracy but slower"
echo "   • Use 'medium' model for best balance"
echo "   • Processing happens on your Mac (private & free)"
echo ""
echo "📁 To activate this environment in future:"
echo "   cd '$PWD'"
echo "   source whisper-env/bin/activate"
echo ""
echo "✅ Ready to process unlimited audio files for FREE!"
